### ISSUE TITLE
[Feature request] Electron standalone

### ISSUE THREAD

**Issue by parkerlreed** [tango-adb/feedback#4]
**Describe the solution you'd like**

I apologize if I've brought this up in a comment before.

Would be great to have WebADB as more of a standalone application using electron.

It is by far the best ADB toolkit hands down web or not.

**Describe alternatives you've considered**

Setting WebADB as a Chrome shortcut. Doesn't work with my main browser so I've been having to keep Edge downloaded just for one website.

**Additional context**

Electron requires the application to call the USB device list itself. There is no native dialog popup like on normal Chrome/Chromium.

https://gist.github.com/jkleinsc/231437c733f6a5ba187c64d53a08cda2

https://github.com/electron/electron/issues/36615

**Comment by yume-chan** [comment]
Blocking on https://github.com/electron/forge/issues/2633

I have done some explorations about USB and TCP connection support, but I can't build my project.

**Comment by yume-chan** [comment]
The desktop app is now available: https://help.tangoapp.dev/blog/2024/06/05/desktop-app/

**Comment by parkerlreed** [comment]
> The desktop app is now available: https://help.tangoapp.dev/blog/2024/06/05/desktop-app/

Thank you! The Linux download fails in the browser (Firefox) as a 404 (subsequently clicking the link only downloads the resulting HTML page)

Grabbing from wget worked fine

```
wget https://app.tangoapp.dev/files/0.1.0/linux/x86-64/tango-bridge
```

**Comment by parkerlreed** [comment]
This is amazing! Finally able to use it in Firefox as the bridge handles TCPIP/USB. Thank you so much!

**Comment by rafi16jan** [comment]
Mentioning OP of [#618](https://github.com/yume-chan/ya-webadb/issues/618) @garywill and other fellow firefox users, I forked the old ya-webadb and add this little polyfill to enable add websocket device dropdown. Theoretically this enables every browser that supports ws:// or wss://

https://github.com/rafi16jan/ya-webadb/commit/4453255c8e0207ad14f3754b086ad710af862613
